add testng homework
ladap1999/TAF_AQA18 pull request #1
Opened 2022-12-04 01:19 UTC by ladap1999

2022-12-13 09:13 UTC, wildpioneer requested changes

2022-12-13 09:13 UTC, wildpioneer commented on src/main/java/com/calculator/Calculator.java
> +    public double div(int firstNumber, int secondNumber){
возвращаемое значение должно быть int для этого метода

2022-12-13 09:13 UTC, wildpioneer commented on src/test/java/tests/CalculatorIntegerTests.java
> +        Assert.assertEquals(calculator.div(18, 0), Double.POSITIVE_INFINITY);
Отсутствует тест на Double.NaN

2023-01-09 13:35 UTC, ladap1999 commented on src/main/java/com/calculator/Calculator.java
> +    public double div(int firstNumber, int secondNumber){
Изменила тип возвращаемого значения на int

2023-01-09 13:36 UTC, ladap1999 commented on src/test/java/tests/CalculatorIntegerTests.java
> +        Assert.assertEquals(calculator.div(18, 0), Double.POSITIVE_INFINITY);
Добавила тест на Double.NaN

2023-01-09 21:26 UTC, wildpioneer commented
Проверено

2023-01-09 21:26 UTC, closed without merging