add selenium_wd_homework
ladap1999/TAF_AQA18 pull request #2
Opened 2022-12-10 19:58 UTC by ladap1999

2022-12-13 09:21 UTC, wildpioneer requested changes

2022-12-13 09:21 UTC, wildpioneer commented on src/test/resources/config.properties
> -url=https://aqa04onl01.testrail.io/
Ты удалила данный файл и теперь ничего не работает

2023-01-09 13:57 UTC, ladap1999 commented on src/test/resources/config.properties
> -url=https://aqa04onl01.testrail.io/
Добавила файл config.properties

2023-01-09 21:22 UTC, wildpioneer commented
Проверено

2023-01-09 21:22 UTC, closed without merging