Page object homework
ladap1999/TAF_AQA18 pull request #4
Opened 2022-12-18 00:19 UTC by ladap1999

2022-12-20 08:33 UTC, wildpioneer requested changes

2022-12-20 08:33 UTC, wildpioneer commented on src/test/java/pages/CartPage.java
> +    private final static String pagePath = "/cart.html";
Небольшое замечание. Переменные лучше организовывать блоками, соответственно pagePath лучше поставить перед описанием локаторов

2022-12-20 08:33 UTC, wildpioneer commented on src/test/java/tests/E2ESauceDemoTest.java
> +        Assert.assertTrue(addToCartSteps.addToCart().isPageOpened());
Не совсем согласен с проверкой каждого шага при помощи Assert. 
Один тест - одна конкретная проверка.

2023-01-09 21:19 UTC, ladap1999 commented on src/test/java/pages/CartPage.java
> +    private final static String pagePath = "/cart.html";
Перенесла переменную pagePath

2023-01-09 21:19 UTC, ladap1999 commented on src/test/java/tests/E2ESauceDemoTest.java
> +        Assert.assertTrue(addToCartSteps.addToCart().isPageOpened());
Оставила один конкретный Assert

2023-01-09 21:26 UTC, wildpioneer commented
Проверено

2023-01-09 21:26 UTC, closed without merging