add advancedActions_homework
ladap1999/TAF_AQA18 pull request #5
Opened 2022-12-18 00:22 UTC by ladap1999

2022-12-20 08:43 UTC, wildpioneer requested changes

2022-12-20 08:43 UTC, wildpioneer commented on src/test/java/tests/FileDownloadTest.java
> +        WebElement link = driver.findElement(By.linkText("sample.png"));
Масло масляное. В начале ты ищешь элемент по тексту в ссылке, а затем берешь текст из этого элемента.

2022-12-20 08:43 UTC, wildpioneer commented on src/test/java/tests/FileDownloadTest.java
> +        Assert.assertTrue(waitsService.waitForExistsFile(System.getProperty("user.dir")+"\\" + nameFile));
На лекции мы говорили про символ разделения папок для разных систем.

2022-12-20 08:43 UTC, wildpioneer commented on src/test/java/tests/FileUploadTest.java
> +        String pathToFile = FileUploadTest.class.getClassLoader().getResource("cable.png").getPath().substring(1);
Замечание: У меня здесь не проходит, потому что не везде надо удалять первый символ.

2023-01-09 21:13 UTC, ladap1999 commented on src/test/java/tests/FileDownloadTest.java
> +        WebElement link = driver.findElement(By.linkText("sample.png"));
Заменила поиск элемента по тексту

2023-01-09 21:14 UTC, ladap1999 commented on src/test/java/tests/FileDownloadTest.java
> +        Assert.assertTrue(waitsService.waitForExistsFile(System.getProperty("user.dir")+"\\" + nameFile));
Заменила на File.separator

2023-01-09 21:15 UTC, ladap1999 commented on src/test/java/tests/FileUploadTest.java
> +        String pathToFile = FileUploadTest.class.getClassLoader().getResource("cable.png").getPath().substring(1);
Добавила возможность работы теста на двух системах

2023-01-09 21:25 UTC, wildpioneer commented
Проверено

2023-01-09 21:25 UTC, closed without merging