Wrappers homework
ladap1999/TAF_AQA18 pull request #6
Opened 2023-01-15 19:37 UTC by ladap1999

2023-01-16 19:52 UTC, wildpioneer requested changes

2023-01-16 19:52 UTC, wildpioneer commented on src/test/java/elements/Checkbox.java
> +    public UIElement selectByIndex(int index) {
Что делает этот метод?

2023-01-16 19:52 UTC, wildpioneer commented on src/test/java/elements/Checkbox.java
> +public class Checkbox {
Для checkbox -а, по моему мнению, должны быть три метода
setFlag
removeFlag
isSelected

2023-01-16 19:52 UTC, wildpioneer commented on src/test/java/elements/Checkbox.java
> +    public UIElement selectByText(String text) {
Чек-бокс - выбрать по тексту?

2023-01-16 19:52 UTC, wildpioneer commented on src/test/java/elements/DropDownMenu.java
> +    public DropDownMenu(WebDriver driver, String dropDownId) {
Улучшение: название параметра dropDownId - излишне, потому что ты и так создаешь экземпляр класса DropDown

2023-01-16 19:52 UTC, wildpioneer commented on src/test/java/elements/DropDownMenu.java
> +    public String search(String searchText) {
Так это Search или selectOptionUsingSearch?

2023-01-21 23:10 UTC, ladap1999 commented on src/test/java/elements/Checkbox.java
> +    public UIElement selectByIndex(int index) {
Удалила данный метод

2023-01-21 23:10 UTC, ladap1999 commented on src/test/java/elements/Checkbox.java
> +public class Checkbox {
Реализовала данные методы

2023-01-21 23:12 UTC, ladap1999 commented on src/test/java/elements/Checkbox.java
> +    public UIElement selectByText(String text) {
Удалила этот метод, но реализацию поиска по тексту оставила в setFlag, removeFlag

2023-01-21 23:12 UTC, ladap1999 commented on src/test/java/elements/DropDownMenu.java
> +    public DropDownMenu(WebDriver driver, String dropDownId) {
Исправила

2023-01-21 23:19 UTC, ladap1999 commented on src/test/java/elements/DropDownMenu.java
> +    public String search(String searchText) {
Изменила название метода

2023-01-30 19:34 UTC, wildpioneer commented
Проверено

2023-01-30 19:34 UTC, closed without merging